// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk5xbDWBPahT8sO-ovWYbyw0WyqkO87xs',
    appId: '1:312444557063:web:5dfd60083232661fa3d7a2',
    messagingSenderId: '312444557063',
    projectId: 'wongikan',
    authDomain: 'wongikan.firebaseapp.com',
    storageBucket: 'wongikan.firebasestorage.app',
    measurementId: 'G-4WYE9WZSJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV1SdJUBy4wwhJdB2KDPmNs0__Udeg-Gw',
    appId: '1:312444557063:android:e7ac908b6628d6aea3d7a2',
    messagingSenderId: '312444557063',
    projectId: 'wongikan',
    storageBucket: 'wongikan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJsSV-8wngSGObHHUcLSqjuD3bZMySkLM',
    appId: '1:312444557063:ios:c2b3992bc6d4a877a3d7a2',
    messagingSenderId: '312444557063',
    projectId: 'wongikan',
    storageBucket: 'wongikan.firebasestorage.app',
    iosBundleId: 'com.example.wongiwak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJsSV-8wngSGObHHUcLSqjuD3bZMySkLM',
    appId: '1:312444557063:ios:c2b3992bc6d4a877a3d7a2',
    messagingSenderId: '312444557063',
    projectId: 'wongikan',
    storageBucket: 'wongikan.firebasestorage.app',
    iosBundleId: 'com.example.wongiwak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk5xbDWBPahT8sO-ovWYbyw0WyqkO87xs',
    appId: '1:312444557063:web:eaf344b8ede787e3a3d7a2',
    messagingSenderId: '312444557063',
    projectId: 'wongikan',
    authDomain: 'wongikan.firebaseapp.com',
    storageBucket: 'wongikan.firebasestorage.app',
    measurementId: 'G-N71Z2WC07V',
  );
}
